# Site
repository: parzibyte/cv
# favicon: images/favicon.ico

# Personal info
name: Luis Cabrera Benito
title: Desarrollador freelancer enfocado en la web, software de escritorio y apps móviles
email: parzibyte@gmail.com
website: parzibyte.me

# Social links
twitter_username: parzibyte
github_username:  parzibyte
# dribbble_username: jekyll
 facebook_username: parzibyte.fanpage
# flickr_username: jekyll
instagram_username: parzibyte
#linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: UCroP4BTWjfM0CkGB6AFUoBg
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, me llamo Luis Cabrera Benito y soy un desarrollador freelancer con experiencia en desarrollo web y apps móviles. Además de mi experiencia en el desarrollo web, tengo conocimientos sobre administración de servidores. La mayoría de experiencia que tengo la he obtenido trabajando como un freelancer.

  Los lenguajes que conozco incluyen PHP, JavaScript, Go, CSS, Java, C, Python, Kotlin.

# Projects Section
projects_title: Proyectos

# Experience Section
experience_title: Experiencia

# Education Section
educaton_title: Educación

# More Section
more_title: Un poco más sobre mí
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
